// courses_data.dart

final Map<String, List<List<String>>> coursesData = {
  'Computer Science and Engineering': [
    // Semester 1
    [
      'Mathematics I',
      'Physics',
      'Introduction to Programming',
      'Engineering Graphics',
      'Basic Electrical Engineering',
      'Environmental Science',
      'Programming Lab',
      'Physics Lab',
    ],
    // Semester 2
    [
      'Mathematics II',
      'Chemistry',
      'Data Structures',
      'Digital Logic Design',
      'Engineering Mechanics',
      'Communication Skills',
      'Data Structures Lab',
      'Chemistry Lab',
    ],
    // Semester 3
    [
      'Mathematics III',
      'Discrete Mathematics',
      'Computer Organization',
      'Object Oriented Programming',
      'Operating Systems',
      'Database Management Systems',
      'OOP Lab',
      'DBMS Lab',
    ],
    // Semester 4
    [
      'Design and Analysis of Algorithms',
      'Microprocessors',
      'Software Engineering',
      'Computer Networks',
      'Theory of Computation',
      'Open Elective I',
      'Algorithms Lab',
      'Microprocessors Lab',
    ],
    // Semester 5
    [
      'Compiler Design',
      'Web Technologies',
      'Artificial Intelligence',
      'Elective I',
      'Open Elective II',
      'Web Technologies Lab',
      'AI Lab',
      'Minor Project I',
    ],
    // Semester 6
    [
      'Machine Learning',
      'Cloud Computing',
      'Elective II',
      'Open Elective III',
      'Professional Ethics',
      'Cloud Computing Lab',
      'ML Lab',
      'Minor Project II',
    ],
    // Semester 7
    [
      'Big Data Analytics',
      'Cyber Security',
      'Elective III',
      'Open Elective IV',
      'Seminar',
      'Project Phase I',
    ],
    // Semester 8
    [
      'Internet of Things',
      'Elective IV',
      'Industrial Training',
      'Project Phase II',
    ],
  ],
  'Electronics and Communication Engineering': [
    [
      'Mathematics I',
      'Physics',
      'Basic Electrical Engineering',
      'Engineering Graphics',
      'Programming Fundamentals',
      'Environmental Science',
      'Physics Lab',
      'Programming Lab',
    ],
    [
      'Mathematics II',
      'Chemistry',
      'Electronic Devices',
      'Network Analysis',
      'Engineering Mechanics',
      'Communication Skills',
      'Chemistry Lab',
      'Electronic Devices Lab',
    ],
    [
      'Mathematics III',
      'Signals and Systems',
      'Digital Electronics',
      'Analog Circuits',
      'Electromagnetic Field Theory',
      'Open Elective I',
      'Analog Circuits Lab',
      'Digital Electronics Lab',
    ],
    [
      'Microprocessors and Microcontrollers',
      'Control Systems',
      'Communication Systems',
      'Linear Integrated Circuits',
      'Probability and Random Processes',
      'Open Elective II',
      'Microprocessors Lab',
      'Communication Lab',
    ],
    [
      'VLSI Design',
      'Digital Signal Processing',
      'Antenna and Wave Propagation',
      'Elective I',
      'Open Elective III',
      'DSP Lab',
      'VLSI Lab',
      'Minor Project I',
    ],
    [
      'Embedded Systems',
      'Wireless Communication',
      'Elective II',
      'Open Elective IV',
      'Professional Ethics',
      'Embedded Systems Lab',
      'Wireless Communication Lab',
      'Minor Project II',
    ],
    [
      'Optical Communication',
      'Microwave Engineering',
      'Elective III',
      'Seminar',
      'Project Phase I',
    ],
    [
      'Satellite Communication',
      'Elective IV',
      'Industrial Training',
      'Project Phase II',
    ],
  ],
  'Electrical Engineering': [
    [
      'Mathematics I',
      'Physics',
      'Basic Electrical Engineering',
      'Engineering Graphics',
      'Programming Fundamentals',
      'Environmental Science',
      'Physics Lab',
      'Electrical Lab I',
    ],
    [
      'Mathematics II',
      'Chemistry',
      'Network Theory',
      'Electronics I',
      'Engineering Mechanics',
      'Communication Skills',
      'Chemistry Lab',
      'Electronics Lab I',
    ],
    [
      'Mathematics III',
      'Electrical Machines I',
      'Electromagnetic Fields',
      'Digital Electronics',
      'Measurement and Instrumentation',
      'Open Elective I',
      'Electrical Machines Lab I',
      'Digital Electronics Lab',
    ],
    [
      'Electrical Machines II',
      'Power Systems I',
      'Control Systems',
      'Microprocessors',
      'Power Electronics',
      'Open Elective II',
      'Electrical Machines Lab II',
      'Power Electronics Lab',
    ],
    [
      'Power Systems II',
      'Switchgear and Protection',
      'Renewable Energy Systems',
      'Elective I',
      'Open Elective III',
      'Power Systems Lab',
      'Renewable Energy Lab',
      'Minor Project I',
    ],
    [
      'High Voltage Engineering',
      'Electrical Drives',
      'Elective II',
      'Open Elective IV',
      'Professional Ethics',
      'Drives Lab',
      'High Voltage Lab',
      'Minor Project II',
    ],
    [
      'Smart Grid Technology',
      'Industrial Automation',
      'Elective III',
      'Seminar',
      'Project Phase I',
    ],
    [
      'Electric Vehicle Technology',
      'Elective IV',
      'Industrial Training',
      'Project Phase II',
    ],
  ],
  'Mechanical Engineering': [
    [
      'Mathematics I',
      'Physics',
      'Engineering Mechanics',
      'Engineering Graphics',
      'Basic Electrical Engineering',
      'Environmental Science',
      'Physics Lab',
      'Workshop Practice',
    ],
    [
      'Mathematics II',
      'Chemistry',
      'Thermodynamics',
      'Material Science',
      'Programming Fundamentals',
      'Communication Skills',
      'Chemistry Lab',
      'Material Science Lab',
    ],
    [
      'Mathematics III',
      'Fluid Mechanics',
      'Manufacturing Processes',
      'Strength of Materials',
      'Machine Drawing',
      'Open Elective I',
      'Fluid Mechanics Lab',
      'Manufacturing Lab',
    ],
    [
      'Applied Thermodynamics',
      'Kinematics of Machines',
      'Heat Transfer',
      'Dynamics of Machines',
      'Mechanical Measurements',
      'Open Elective II',
      'Heat Transfer Lab',
      'Dynamics Lab',
    ],
    [
      'Design of Machine Elements',
      'Internal Combustion Engines',
      'Refrigeration and Air Conditioning',
      'Elective I',
      'Open Elective III',
      'IC Engines Lab',
      'RAC Lab',
      'Minor Project I',
    ],
    [
      'Automobile Engineering',
      'Robotics',
      'Elective II',
      'Open Elective IV',
      'Professional Ethics',
      'Automobile Lab',
      'Robotics Lab',
      'Minor Project II',
    ],
    [
      'Industrial Engineering',
      'Finite Element Methods',
      'Elective III',
      'Seminar',
      'Project Phase I',
    ],
    [
      'Operations Research',
      'Elective IV',
      'Industrial Training',
      'Project Phase II',
    ],
  ],
  'Chemical Engineering': [
    [
      'Mathematics I',
      'Physics',
      'Basic Chemical Engineering',
      'Engineering Graphics',
      'Chemistry',
      'Environmental Science',
      'Physics Lab',
      'Chemistry Lab',
    ],
    [
      'Mathematics II',
      'Material Science',
      'Fluid Mechanics',
      'Programming Fundamentals',
      'Engineering Mechanics',
      'Communication Skills',
      'Material Science Lab',
      'Fluid Mechanics Lab',
    ],
    [
      'Mathematics III',
      'Chemical Process Calculations',
      'Thermodynamics',
      'Mechanical Operations',
      'Process Instrumentation',
      'Open Elective I',
      'Mechanical Operations Lab',
      'Instrumentation Lab',
    ],
    [
      'Heat Transfer',
      'Mass Transfer I',
      'Chemical Reaction Engineering I',
      'Process Dynamics and Control',
      'Open Elective II',
      'Heat Transfer Lab',
      'Mass Transfer Lab',
      'Reaction Engineering Lab',
    ],
    [
      'Mass Transfer II',
      'Chemical Reaction Engineering II',
      'Process Equipment Design',
      'Elective I',
      'Open Elective III',
      'Equipment Design Lab',
      'Process Control Lab',
      'Minor Project I',
    ],
    [
      'Biochemical Engineering',
      'Petrochemical Technology',
      'Elective II',
      'Open Elective IV',
      'Professional Ethics',
      'Biochemical Lab',
      'Petrochemical Lab',
      'Minor Project II',
    ],
    [
      'Environmental Engineering',
      'Polymer Technology',
      'Elective III',
      'Seminar',
      'Project Phase I',
    ],
    [
      'Safety and Hazard Management',
      'Elective IV',
      'Industrial Training',
      'Project Phase II',
    ],
  ],
  'Civil Engineering': [
    [
      'Mathematics I',
      'Physics',
      'Engineering Mechanics',
      'Engineering Graphics',
      'Basic Civil Engineering',
      'Environmental Science',
      'Physics Lab',
      'Workshop Practice',
    ],
    [
      'Mathematics II',
      'Chemistry',
      'Building Materials',
      'Surveying',
      'Programming Fundamentals',
      'Communication Skills',
      'Chemistry Lab',
      'Surveying Lab',
    ],
    [
      'Mathematics III',
      'Strength of Materials',
      'Fluid Mechanics',
      'Structural Analysis I',
      'Geotechnical Engineering I',
      'Open Elective I',
      'Strength of Materials Lab',
      'Fluid Mechanics Lab',
    ],
    [
      'Concrete Technology',
      'Structural Analysis II',
      'Geotechnical Engineering II',
      'Transportation Engineering I',
      'Open Elective II',
      'Concrete Lab',
      'Geotechnical Lab',
      'Transportation Lab',
    ],
    [
      'Design of Concrete Structures',
      'Water Resources Engineering',
      'Environmental Engineering I',
      'Elective I',
      'Open Elective III',
      'Water Resources Lab',
      'Environmental Lab',
      'Minor Project I',
    ],
    [
      'Design of Steel Structures',
      'Transportation Engineering II',
      'Environmental Engineering II',
      'Elective II',
      'Open Elective IV',
      'Steel Structures Lab',
      'Transportation Lab II',
      'Minor Project II',
    ],
    [
      'Construction Management',
      'Remote Sensing and GIS',
      'Elective III',
      'Seminar',
      'Project Phase I',
    ],
    [
      'Disaster Management',
      'Elective IV',
      'Industrial Training',
      'Project Phase II',
    ],
  ],
};